---
abstract: 'Template Toolkit dumper plugin using Data::Printer'
author:
  - 'Stephen Thirlwall <sdt@cpan.org>'
build_requires:
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  HTML::Entities: 0
  Template: 0
  Term::ANSIColor: 0
  Test::Builder: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-DataPrinter
requires:
  Data::Printer: 0
  HTML::FromANSI::Tiny: 0
  Hash::Merge::Simple: 0
  Template::Plugin: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-DataPrinter
  homepage: http://search.cpan.org/dist/Template-Plugin-DataPrinter
  repository: git://github.com/sdt/template-plugin-dataprinter.git
version: 0.010
